name: Secrets Check

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for env leaks
        run: |
          ! grep -R "PRIVATE_KEY" .

